# This is a basic workflow to help you get started with Actions

name: svn-sync

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan mainline branches and report all findings: 
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  #schedule:
    #- cron: '30 0 1,15 * *' # Scheduled for 00:30 UTC on both the 1st and 15th of the month

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: svn cloning
        run: |
          sudo apt-get update
          sudo apt-get install subversion
          svn co http://plugins.svn.wordpress.org/side-menu/trunk
          pwd
          
      - uses: actions/upload-artifact@master
        with:
          name: repo-path
          path: trunk/
          
  clone:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      
      #commit the code to git repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change

          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: main

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional commit user and author settings
          commit_user_name: my-bot # defaults to "github-actions[bot]"
          commit_user_email: shreyapohekar@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: bot <actions@github.com> # defaults to author of the commit that triggered the run

          # Optional. Option used by `git-status` to determine if the repository is 
          # dirty. See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'

          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          add_options: '-u'

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          push_options: '--force'
    
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
    
          # Optional. Skip internal call to `git fetch`
          skip_fetch: true    
    
          # Optional. Skip internal call to `git checkout`
          skip_checkout: true

          disable_globbing: true
 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - run: ls -la
