# This is a basic workflow to help you get started with Actions

name: svn-sync

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan mainline branches and report all findings: 
  push:
    branches: ["master", "main"]
  # Schedule the CI job (this method uses cron syntax):
  #schedule:
  #  - cron: '*/10 * * * *' # Scheduled for 00:30 UTC on both the 1st and 15th of the month

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: svn cloning
        run: |
          sudo apt-get update
          sudo apt-get install subversion
          svn co http://plugins.svn.wordpress.org/side-menu/trunk
          pwd
          
      - uses: actions/upload-artifact@master
        with:
          name: repo-path
          path: trunk/
          
  clone:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        
      - run: pwd
        
      - uses: actions/download-artifact@master
        with:
          name: repo-path
          path: trunk/
      - run: ls -la trunk/
      - run: pwd
      
      
      #commit the code to git repo : https://github.com/marketplace/actions/add-commit
      - uses: EndBug/add-and-commit@v9
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          message: Automated Change
        
          author_name: shreya
          author_email: shreyapohekar@gmail.com
          commit: --signoff
          committer_name: shreya
          committer_email: shreya@example.com
          add: '.'
          #pull: true 
          fetch: true
          # Default: github_actor
          default_author: github_actor
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - run: ls -la
